version: "3.7"
services:
  app:
    build:
      args:
        user: jolti
        uid: 1000
      dockerfile: dockerFile
    image: dtotoxml
    container_name: dtotoxml-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - dtotoxml
  


  nginx:
    image: nginx:1.23-alpine
    container_name: dtotoxml-server
    restart: unless-stopped
    ports:
      - 6060:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dtotoxml
    
networks:
  dtotoxml:
    driver: bridge